name: three_o
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.1.0
  http: ^1.4.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.11
  riverpod_generator: ^2.4.2
  freezed: ^2.5.3
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - .env.development

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_icon.png'
